// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-O0Qdc9NxysyzyuEKYXmkGtaCkuyw1gc',
    appId: '1:78205147348:web:c66079367414fc72cd8341',
    messagingSenderId: '78205147348',
    projectId: 'evoyou-e4d6b',
    authDomain: 'evoyou-e4d6b.firebaseapp.com',
    storageBucket: 'evoyou-e4d6b.firebasestorage.app',
    measurementId: 'G-HMPDWGM1JV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_l7OAcDi1geot9Ln6maouu7m8sUPDMls',
    appId: '1:78205147348:android:d2094ce72669d3ebcd8341',
    messagingSenderId: '78205147348',
    projectId: 'evoyou-e4d6b',
    storageBucket: 'evoyou-e4d6b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzlJSlJMQQq4xlSN6QcXmF1_pAe1b7EZg',
    appId: '1:78205147348:ios:fb18a35d1702a51bcd8341',
    messagingSenderId: '78205147348',
    projectId: 'evoyou-e4d6b',
    storageBucket: 'evoyou-e4d6b.firebasestorage.app',
    iosBundleId: 'com.example.evoyouAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzlJSlJMQQq4xlSN6QcXmF1_pAe1b7EZg',
    appId: '1:78205147348:ios:fb18a35d1702a51bcd8341',
    messagingSenderId: '78205147348',
    projectId: 'evoyou-e4d6b',
    storageBucket: 'evoyou-e4d6b.firebasestorage.app',
    iosBundleId: 'com.example.evoyouAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-O0Qdc9NxysyzyuEKYXmkGtaCkuyw1gc',
    appId: '1:78205147348:web:9f3729ee9abd8dc7cd8341',
    messagingSenderId: '78205147348',
    projectId: 'evoyou-e4d6b',
    authDomain: 'evoyou-e4d6b.firebaseapp.com',
    storageBucket: 'evoyou-e4d6b.firebasestorage.app',
    measurementId: 'G-63B9WTYP2G',
  );

}